export const OUTBOX_EVENT_TRANSACTION_CREATED = 'transaction.created';

export const DEFAULT_TOPIC_TRANSACTION_CREATED = 'transaction_created';
export const DEFAULT_TOPIC_TRANSACTION_STATUS_UPDATED =
  'transaction_status_updated';

export const KAFKA_CONFIG = {
  BROKERS: 'KAFKA_BROKERS',
  ENABLED: 'KAFKA_ENABLED',
  TOPIC_CREATED: 'KAFKA_TOPIC_TRANSACTION_CREATED',
  TOPIC_STATUS_UPDATED: 'KAFKA_TOPIC_TRANSACTION_STATUS_UPDATED',
  CLIENT_ID_API: 'KAFKA_CLIENT_ID_API',
  CLIENT_ID_ANTI_FRAUD: 'KAFKA_CLIENT_ID_ANTI_FRAUD',
  GROUP_STATUS_CONSUMER: 'KAFKA_GROUP_TRANSACTION_STATUS',
  GROUP_ANTI_FRAUD: 'KAFKA_GROUP_ANTI_FRAUD',
  ENABLE_OUTBOX_RELAY: 'ENABLE_OUTBOX_RELAY',
} as const;
